<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto

namespace GPBMetadata;

class Log
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
÷
	log.protoextend.ali.log"%
Content
Key (	
Value (	">
Log
Time ()
Contents (2.extend.ali.log.Content"$
LogTag
Key (	
Value (	"‡
LogGroup!
Logs (2.extend.ali.log.Log
Reserved (	
Topic (	
Source (	\'
LogTags (2.extend.ali.log.LogTag";
LogGroupList+
	logGroups (2.extend.ali.log.LogGroupbproto3'
        , true);

        static::$is_initialized = true;
    }
}

