<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto

namespace Extend\Ali\Log;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>extend.ali.log.LogGroupList</code>
 */
class LogGroupList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .extend.ali.log.LogGroup logGroups = 1;</code>
     */
    private $logGroups;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Extend\Ali\Log\LogGroup[]|\Google\Protobuf\Internal\RepeatedField $logGroups
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Log::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .extend.ali.log.LogGroup logGroups = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLogGroups()
    {
        return $this->logGroups;
    }

    /**
     * Generated from protobuf field <code>repeated .extend.ali.log.LogGroup logGroups = 1;</code>
     * @param \Extend\Ali\Log\LogGroup[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLogGroups($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Extend\Ali\Log\LogGroup::class);
        $this->logGroups = $arr;

        return $this;
    }

}

