<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto

namespace Extend\Ali\Log;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>extend.ali.log.LogGroup</code>
 */
class LogGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .extend.ali.log.Log Logs = 1;</code>
     */
    private $Logs;
    /**
     * reserved fields
     *
     * Generated from protobuf field <code>string Reserved = 2;</code>
     */
    protected $Reserved = '';
    /**
     * Generated from protobuf field <code>string Topic = 3;</code>
     */
    protected $Topic = '';
    /**
     * Generated from protobuf field <code>string Source = 4;</code>
     */
    protected $Source = '';
    /**
     * Generated from protobuf field <code>repeated .extend.ali.log.LogTag LogTags = 6;</code>
     */
    private $LogTags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Extend\Ali\Log\Log[]|\Google\Protobuf\Internal\RepeatedField $Logs
     *     @type string $Reserved
     *           reserved fields
     *     @type string $Topic
     *     @type string $Source
     *     @type \Extend\Ali\Log\LogTag[]|\Google\Protobuf\Internal\RepeatedField $LogTags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Log::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .extend.ali.log.Log Logs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLogs()
    {
        return $this->Logs;
    }

    /**
     * Generated from protobuf field <code>repeated .extend.ali.log.Log Logs = 1;</code>
     * @param \Extend\Ali\Log\Log[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Extend\Ali\Log\Log::class);
        $this->Logs = $arr;

        return $this;
    }

    /**
     * reserved fields
     *
     * Generated from protobuf field <code>string Reserved = 2;</code>
     * @return string
     */
    public function getReserved()
    {
        return $this->Reserved;
    }

    /**
     * reserved fields
     *
     * Generated from protobuf field <code>string Reserved = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReserved($var)
    {
        GPBUtil::checkString($var, True);
        $this->Reserved = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Topic = 3;</code>
     * @return string
     */
    public function getTopic()
    {
        return $this->Topic;
    }

    /**
     * Generated from protobuf field <code>string Topic = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->Topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Source = 4;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->Source;
    }

    /**
     * Generated from protobuf field <code>string Source = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->Source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .extend.ali.log.LogTag LogTags = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLogTags()
    {
        return $this->LogTags;
    }

    /**
     * Generated from protobuf field <code>repeated .extend.ali.log.LogTag LogTags = 6;</code>
     * @param \Extend\Ali\Log\LogTag[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLogTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Extend\Ali\Log\LogTag::class);
        $this->LogTags = $arr;

        return $this;
    }

}

